spring:
  application:
    name: api-gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: demo-service
        uri: lb://user-service
        predicates:
        - Path=/user/**

server:
  port: 8200

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/